---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian12
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: debian13
    image: "geerlingguy/docker-debian13-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: debian12-resolved
    image: "geerlingguy/docker-debian13-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

  - name: debian13-resolved
    image: "geerlingguy/docker-debian13-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /ansible-tmp
      deprecation_warnings: false
  inventory:
    host_vars:
      debian12:
        general_hostname: "debian12"
        general_ignore_hostname_task: true
        general_ignore_ssh_key_deployment: true
        general_ip_address: 10.0.0.1
      debian13:
        general_hostname: "debian13"
        general_ignore_ssh_key_deployment: true
        general_ignore_hostname_task: true
        general_root_setup_enabled: true
        general_root_password_salt: "testsalt"
        general_root_password: "test"
        general_ip_address: 10.0.0.2
      debian12-resolved:
        general_hostname: "debian12.resolved"
        general_ignore_ssh_key_deployment: true
        general_ignore_hostname_task: true
        general_root_setup_enabled: true
        general_root_password_salt: "testsalt"
        general_root_password: "test"
        general_ip_address: 10.0.0.3
      debian13-resolved:
        general_hostname: "debian13.resolved"
        general_ignore_ssh_key_deployment: true
        general_ignore_hostname_task: true
        general_ip_address: 10.0.0.4
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
